import { describe, expect, it } from 'vitest'
import { tokenizeXmlLine } from '../src/utils/reports/tokenizeXmlLine'

describe('tokenizeXmlLine', () => {
  it('preserves the line verbatim across tokens', () => {
    const line = '  <report_id>16652345060496736316</report_id>'

    expect(
      tokenizeXmlLine(line)
        .map((t) => t.value)
        .join(''),
    ).toBe(line)
  })

  it('marks the tag name and the element text apart', () => {
    const tokens = tokenizeXmlLine('<domain>example.com</domain>')

    expect(tokens.find((t) => t.kind === 'tagName')?.value).toBe('domain')
    expect(tokens.find((t) => t.kind === 'text')?.value).toBe('example.com')
  })

  it('splits attributes into name and quoted value', () => {
    const tokens = tokenizeXmlLine('<?xml version="1.0" encoding="UTF-8" ?>')

    expect(
      tokens.filter((t) => t.kind === 'attrName').map((t) => t.value),
    ).toEqual(['version', 'encoding'])
    expect(
      tokens.filter((t) => t.kind === 'attrValue').map((t) => t.value),
    ).toEqual(['"1.0"', '"UTF-8"'])
  })

  it('keeps a comment in one token', () => {
    const tokens = tokenizeXmlLine('<!-- generated by example -->')

    expect(tokens).toEqual([
      { kind: 'comment', value: '<!-- generated by example -->' },
    ])
  })

  it('round-trips a line with no markup', () => {
    expect(tokenizeXmlLine('plain text')).toEqual([
      { kind: 'text', value: 'plain text' },
    ])
  })
})
