version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    groups:
      radix-ui:
        patterns:
          - '@radix-ui/*'
      tanstack:
        patterns:
          - '@tanstack/*'
      drizzle:
        patterns:
          - 'drizzle-*'
      types:
        patterns:
          - '@types/*'
        dependency-type: 'development'

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
    labels:
      - dependencies
      - github-actions
